env:
  es2021: true
  node: true
  jest: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - '@typescript-eslint'
  - eslint-plugin-import-helpers
  - prettier

rules:
  prettier/prettier: error

  no-console: 'off'
  camelcase: 'off'
  class-methods-use-this: 'off'
  import/prefer-default-export: 'off'

  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: "_"
      varsIgnorePattern: "_"

  '@typescript-eslint/naming-convention':
    - error
    -
      selector: interface
      format:
        - StrictPascalCase
      prefix:
        - I

  import-helpers/order-imports:
    - warn
    -
      newlinesBetween: always
      groups:
        - module
        - /entity/
        - /repository/
        - /useCases/
        - /error/
        - /providers/
        - - parent
          - sibling
          - index
      alphabetize:
        order: asc
        ignoreCase: true

  import/extensions:
    - error
    - ignorePackages
    -
      ts: never

settings:
  import/resolver:
    typescript: {}
